apiVersion: v1
kind: Pod
metadata:
  name: data-uploader-fg
spec:
  restartPolicy: Never
  containers:
  - name: data-uploader
    imagePullPolicy: Always
    image: registry.ferrari.snucse.org:30443/attention-x/data-uploader
    args: [ "--root_folder_id", "1-jgvacbmvgOExPRm4rpqjktct37LmTc5" ]
    volumeMounts:
    - name: google-credentials-volume
      mountPath: /mount
    - name: vision-assistant-pv
      mountPath: "/input"
    resources:
      limits:
        cpu: "50"
        memory: "128Gi"
  volumes:
  - name: vision-assistant-pv
    persistentVolumeClaim:
      claimName: vision-assistant-pvc
  - name: google-credentials-volume
    secret:
      secretName: google-credentials
