apiVersion: v1
kind: Pod
metadata:
  name: vision-assistant-experiment-bg
spec:
  restartPolicy: Never
  containers:
  - name: experiment-container
    image: "registry.ferrari.snucse.org:30443/attention-x/drive-vision-assistant-experiment:latest"
    # Just spin & wait forever
    # torchrun --nproc_per_node=1 train.py --cfg-path /train-config/drive_finetune.yaml
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "50"
        memory: "400Gi"
        nvidia.com/gpu: "4"
    envFrom:
      - secretRef:
            name: wandb-secret
    volumeMounts:
    - mountPath: "/input"
      name: vision-assistant-pv
    - mountPath: "/output"
      name: vision-assistant-pv
    - mountPath: "/train-config"
      name: train-config-pv
  volumes:
  - name: vision-assistant-pv
    persistentVolumeClaim:
      claimName: vision-assistant-pvc
  - name: train-config-pv
    configMap:
      name: train-config